version: "3.9"
services:
  database:
    image: mysql:8
    container_name: product_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: Product
      MYSQL_USER: root
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  products-service:
    image: postechfiap01/products-service:latest
    container_name: products-service
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MYSQL_HOST=database
      - MYSQL_USER=root
      - MYSQL_PASSWORD=admin123
      - MYSQL_DATABASE=Product
    depends_on:
      - database

volumes:
  db_data:
