services:
  database:
    image: mysql:8
    container_name: product_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: Product
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    image: node:20
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=mysql://root:admin123@database:3306/Product
    command: sh -c "npm install && npx prisma migrate deploy"
    depends_on:
      database:
        condition: service_healthy

  products-service:
    image: postechfiap01/products-service:latest
    container_name: products-service
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MYSQL_HOST=database
      - MYSQL_USER=root
      - MYSQL_PASSWORD=admin123
      - MYSQL_DATABASE=Product
    depends_on:
      - database

volumes:
  db_data:
