apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-mysql-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-03d19568ab29cba44
    volumeAttributes:
      accessPointId: fsap-08df5a969cc44dbce
